pockethive:
  worker:
    inputs:
      autowire: true
  outputs:
    rabbit:
      exchange: ${POCKETHIVE_OUTPUT_RABBIT_EXCHANGE}
      routingKey: ${POCKETHIVE_OUTPUT_RABBIT_ROUTING_KEY}
  control-plane:
    exchange: ${POCKETHIVE_CONTROL_PLANE_EXCHANGE}
    swarm-id: ${POCKETHIVE_CONTROL_PLANE_SWARM_ID}
    instance-id: ${POCKETHIVE_CONTROL_PLANE_INSTANCE_ID}
    control-queue-prefix: ${POCKETHIVE_CONTROL_PLANE_CONTROL_QUEUE_PREFIX}
    worker:
      role: payload-generator
      skip-self-signals: false
    manager:
      enabled: false
  workers:
    payload-generator:
      config:
        ratePerSec: 1.0
        singleRequest: false
      template:
        body: |
          <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
                            xmlns:req="http://example.com/req/v1">
            <soapenv:Header>
              <req:ClientId>{{ record.clientId }}</req:ClientId>
            </soapenv:Header>
            <soapenv:Body>
                <req:PingRequest tick="{{ seed.headers['x-ph-scheduler-tick'] | default('n/a') }}">
                  <req:payload>{{ seed.body | default(record.payload) }}</req:payload>
                </req:PingRequest>
            </soapenv:Body>
          </soapenv:Envelope>
        headers:
          content-type: text/xml
          soapaction: ping

logging:
  level:
    io.pockethive.payload.generator: INFO
    io.pockethive.worker.sdk.input.SchedulerWorkInput: DEBUG
    io.pockethive.worker.sdk.input.SchedulerStates: DEBUG

management.prometheus.metrics.export.pushgateway.job: ${POCKETHIVE_CONTROL_PLANE_SWARM_ID}
management.prometheus.metrics.export.pushgateway.grouping-key.instance: ${POCKETHIVE_CONTROL_PLANE_INSTANCE_ID}
