import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "category",
      label: "Presentation",
      items: ["guides/presentation/interactive-pockethive-overview"],
    },
    {
      type: "category",
      label: "Onboarding",
      items: [
        "guides/onboarding/start-here",
        "guides/onboarding/quickstart-15min",
        "guides/onboarding/first-scenario",
      ],
    },
    {
      type: "category",
      label: "Workers",
      items: ["guides/workers-basics", "guides/workers-advanced"],
    },
    {
      type: "category",
      label: "Templating",
      items: ["guides/templating-basics", "guides/templating-advanced"],
    },
    {
      type: "category",
      label: "Scenarios",
      items: [{ type: "autogenerated", dirName: "scenarios" }],
    },
    {
      type: "category",
      label: "Reference",
      items: [
        "ARCHITECTURE",
        "ORCHESTRATOR-REST",
        "USAGE",
        "observability",
        "correlation-vs-idempotency",
      ],
    },
  ],
};

export default sidebars;
