import io.pockethive.requesttemplates.RequestTemplateProtocol;
import io.pockethive.worker.sdk.auth.AuthType;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Responsibility: export compiled runtime vocabulary as the intake package's read-only schema projection.
 * Must not: parse Java sources, define runtime values, reseal the package or decide intake readiness.
 * Contract: RESP-INTAKE-RUNTIME-VOCABULARY — docs/architecture/runtime-responsibilities.md#resp-intake-runtime-vocabulary.
 */
public final class ExportRuntimeVocabulary {
    private ExportRuntimeVocabulary() {
    }

    public static void main(String[] arguments) throws IOException {
        if (arguments.length < 1 || arguments.length > 2
                || arguments.length == 2 && !arguments[1].equals("--check")) {
            throw new IllegalArgumentException("Usage: ExportRuntimeVocabulary.java OUTPUT [--check]");
        }
        Path output = Path.of(arguments[0]).toAbsolutePath();
        String expected = schema();
        if (arguments.length == 2) {
            if (!Files.isRegularFile(output)
                    || !Files.readString(output, StandardCharsets.UTF_8).equals(expected)) {
                System.err.println("Intake runtime vocabulary is missing or stale; run tools/intake-contracts/generate.sh.");
                System.exit(1);
            }
            System.out.println("Intake runtime vocabulary matches its compiled owners.");
            return;
        }
        Files.createDirectories(output.getParent());
        Files.writeString(output, expected, StandardCharsets.UTF_8);
        if (!Files.readString(output, StandardCharsets.UTF_8).equals(expected)) {
            throw new IOException("Generated intake runtime vocabulary failed readback verification.");
        }
        System.out.println("Generated and verified intake runtime vocabulary.");
    }

    private static String schema() {
        String auth = definition("authType", "AuthType.values()/key() in common/auth-contracts",
            Arrays.stream(AuthType.values()).map(AuthType::key).toList());
        String protocol = definition("requestTemplateProtocol", "RequestTemplateProtocol.values()/name() in common/request-templates",
            Arrays.stream(RequestTemplateProtocol.values()).map(Enum::name).toList());
        return """
            {
              "$schema": "http://json-schema.org/draft-07/schema#",
              "title": "PocketHive runtime vocabulary for intake",
              "$comment": "Generated by tools/intake-contracts/ExportRuntimeVocabulary.java from compiled canonical owners. Read-only projection; do not edit. Contract: RESP-INTAKE-RUNTIME-VOCABULARY in docs/architecture/runtime-responsibilities.md. This snapshot does not establish deployed capabilities or intake readiness.",
              "definitions": {
            """ + auth + ",\n" + protocol + "\n  }\n}\n";
    }

    private static String definition(String name, String owner, List<String> values) {
        // Enum names and AuthType.key() contain only enum-identifier characters and hyphens.
        String entries = values.stream().map(value -> "        \"" + value + "\"")
            .collect(Collectors.joining(",\n"));
        return "    \"" + name + "\": {\n"
            + "      \"$comment\": \"Generated from " + owner + "; do not edit.\",\n"
            + "      \"type\": \"string\",\n"
            + "      \"enum\": [\n" + entries + "\n      ]\n    }";
    }
}
