kind: component
component:
  name: stack
  project: pockethive
deployment:
  adapter: ansible
  actions:
    deploy:
      playbook: ansible/deploy.yml
    remove:
      playbook: ansible/remove.yml
    update:
      playbook: ansible/update.yml
requirements:
  environment:
    - DOCKER_REGISTRY
    - POCKETHIVE_VERSION
    - POCKETHIVE_CONTROL_PLANE_ORCHESTRATOR_IMAGE_REPOSITORY_PREFIX
