export const COMPANION_OAUTH_CLIENT_ID = 'pockethive-vscode';
export const COMPANION_OAUTH_CALLBACK_HOST = '127.0.0.1';
export const COMPANION_OAUTH_CALLBACK_PORT = 52_000;
export const COMPANION_OAUTH_CALLBACK_PATH = '/callback';
export const COMPANION_OAUTH_REDIRECT_URI =
  `http://${COMPANION_OAUTH_CALLBACK_HOST}:${COMPANION_OAUTH_CALLBACK_PORT}${COMPANION_OAUTH_CALLBACK_PATH}`;
