ARG RUNTIME_IMAGE=pockethive-jvm-base:latest

FROM ${RUNTIME_IMAGE}
COPY .local-jars/log-aggregator-service.jar /app/app.jar
COPY log-aggregator-service/entrypoint.sh /app/entrypoint.sh
ENTRYPOINT ["/app/entrypoint.sh"]
