name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Run Maven tests
        run: mvn -B -ntp test

      - name: Install worker dependencies and build starter examples
        run: |
          set -euo pipefail
          rm -rf ~/.m2/repository/io/pockethive
          REVISION="$(cat VERSION)"
          mvn -B -ntp -N install
          mvn -B -ntp install:install-file -Dfile=pom.xml -DgroupId=io.pockethive -DartifactId=pockethive-mvp -Dversion="$REVISION" -Dpackaging=pom
          mvn -B -ntp -pl common/worker-sdk -am install -DskipTests -Drevision="$REVISION"
          mvn -B -ntp -f examples/worker-starter/pom.xml verify -Drevision="$REVISION"
