name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Build and test
        run: mvn -B verify
      - name: Cucumber
        if: ${{ hashFiles('**/*.feature') != '' }}
        run: mvn -B test -Dcucumber
      - name: Lint
        if: ${{ hashFiles('package.json') != '' }}
        run: npm run lint
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v5
