name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Run Maven tests
        run: mvn -B -ntp test

      - name: Install PocketHive parent POM
        run: mvn -B -ntp -N install

      - name: Install parent placeholder for worker starter builds
        run: mvn -B -ntp install:install-file -Dfile=pom.xml -DgroupId=io.pockethive -DartifactId=pockethive-mvp -Dversion=\${revision} -Dpackaging=pom

      - name: Install PocketHive Worker SDK
        run: mvn -B -ntp -pl common/worker-sdk -am install -DskipTests

      - name: Build worker starter examples
        run: mvn -B -ntp -f examples/worker-starter/pom.xml verify -Drevision="$(cat VERSION)"
